### ISSUE TITLE
CSS Code Is Broken

### ISSUE THREAD

**Issue by OscarDeer** [codeforum-org/WebWareBox#3]
So, after some Font-Awesome Icons were added to each Page, it was only after they were added that the Site isn't Rendering in any CSS Code.

The Icons-Script seems to have tampered with every part of the CSS and thus' has broken the Site's Design and turned it into something that you would find on the 90's Internet.

Screenshot as Evidence:
![Screenshot from 2019-06-22 16-19-44](https://user-images.githubusercontent.com/39654594/59965810-e4105d00-950a-11e9-9ecf-9a74576ec4c2.png)

**Comment by malcolmjr96** [comment]
Make sure it's the correct path. I tried it on a Linux based system and no issues.
