### ISSUE TITLE
Finish Developing the index.html Page

### ISSUE THREAD

**Issue by malcolmjr96** [codeforum-org/WebWareBox#4]
What needs to be done:
- Recently-Added Section
- News-Container(Display a small amount of Site-News and then provide a Link to read more)
- Make the Buttons navigate to other Pages - DONE!

**Comment by Dan-Kode** [comment]
I'm closing this as _index.html_ is now _index.php_. Any work on _index.html_ should be scrapped as it will be replaced by _index.php_.
