### ISSUE TITLE
Add hovering effects to menu items

### ISSUE THREAD

**Issue by malcolmjr96** [codeforum-org/WebWareBox#9]

**Comment by Code-Block** [comment]
I have tried adding a Shadow-Effect using the CSS :hover Selector and using `box-shadow`

Right now, I haven't had any Luck, what so ever.

**Comment by malcolmjr96** [comment]
Okay, I got this working! I changed the navigation to the <nav> tag, used an unordered list within that I had the list items which I'm using as the different nav items.

The unordered list items are all the same class so then I was able to apply to :hover onto them.
